name: care_flow
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  get_it: ^7.2.0
  connectivity_plus: ^3.0.4
  image_picker: ^0.8.7+3
  tflite: ^1.1.2
  firebase_core: ^2.11.0
  firebase_storage: ^11.2.3
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  fluttertoast: ^8.2.1
  dio: ^5.1.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.4.0
  auto_size_text: ^3.0.0
  dotted_line: ^3.2.2
  path_provider: ^2.0.15
  http: ^0.13.6
  path: ^1.8.2
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/
     - assets/images/login.gif
     - assets/images/splash.gif
     - assets/images/corona.jpg
     - assets/images/lung.jpg
     - assets/images/lung1.jpg
     - assets/images/patient.jpg
     - assets/images/doctor.jpg
     - assets/images/bone.jpg
     - assets/images/brain.jpg
     - assets/images/ear.jpg
     - assets/images/eye.jpg
     - assets/images/heart.jpg
     - assets/images/skin.jpg
     - assets/images/Urologist.jpg
     - assets/images/consultation.jpg
     - assets/images/drug.jpg
     - assets/images/chat.jpg
     - assets/images/diagnosis.jpg
     - assets/images/patient_login.png
     - assets/images/lab.jpg



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

